import "../styles/globals.css";
import Head from "next/head";
import { useState } from "react";
import { Main } from "component/layout/Main";
import { Header } from "component/layout/Header";

function MyApp({ Component, pageProps }) {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header onClick={() => setDarkMode(!darkMode)} />
      <Main>
        <Component {...pageProps} />
      </Main>
    </div>
  );
}

export default MyApp;
