import "styles/globals.css";
import Head from "next/head";
import { useState } from "react";
import { Main } from "component/layout/Main";
import { Header } from "component/layout/Header";
import { usePriceRangeMenuSelector } from "component/hooks/usePriceRangeMenuSelector";
import { useChatBotGpt } from "component/hooks/useChatBotGpt";

function MyApp({ Component, pageProps }) {
  const [darkMode, setDarkMode] = useState(false);
  const counter = usePriceRangeMenuSelector();
  const chat = useChatBotGpt();

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>My-Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="public/favicon.ico" />
      </Head>
      <Header handleClick={() => setDarkMode(!darkMode)} />
      <Main>
        <Component {...pageProps} {...counter} {...chat} />
      </Main>
    </div>
  );
}

export default MyApp;
